---

- name: MARATHON DEBIAN | Add repository key
  apt_key:
    id: "{{ marathon_apt_repository_keyserver_revc }}"
    keyserver: "{{ marathon_apt_repository_keyserver }}"
    state: present

- name: MARATHON DEBIAN | Add repository
  apt_repository:
    repo: "{{ marathon_apt_repository_url }}"
    state: present
    update_cache: yes
