---

- name: MARATHON | Manage Debian environment
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: MARATHON | Manage RedHat environment
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: MARATHON | Installation
  package:
    name: marathon
    state: present

# - name: MARATHON | Create Marathon directory
#   file:
#     state: directory
#     path: /etc/marathon/conf
#     mode: 0755
#     owner: root
#     group: root
#
# - name: MARATHON | Configure Marathon on remote system
#   template:
#     src: "{{ item }}.j2"
#     dest: "/{{ item }}"
#     owner: root
#     group: root
#     mode: 0664
#   with_items:
#     - "etc/default/marathon"
#   notify: Restart marathon
#
# - name: Configure Marathon systemd service
#   template:
#     src: "{{ item }}.j2"
#     dest: "/{{ item }}"
#     owner: root
#     group: root
#     mode: 0664
#   with_items:
#     - "lib/systemd/system/mesos-master.service"
#   when: inventory_hostname in groups['master']
#   notify:
#     - Restart marathon
