---

- name: MARATHON | Manage Debian environment
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: MARATHON | Manage RedHat environment
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: MARATHON | Installation
  package:
    name: marathon
    state: present

- name: MARATHON | Configuration
  template:
    src: etc/default/marathon.j2
    dest: /etc/default/marathon
    owner: root
    group: root
    mode: 0664
  notify: Restart marathon
