---

###
# MARATHON
###

# Debian
# Setup
marathon_apt_repository_keyserver: hkp://keyserver.ubuntu.com:80
marathon_apt_repository_keyserver_revc: DF7D54CBE56151BF
marathon_apt_repository_url: "deb http://repos.mesosphere.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} main"

# RedHat
marathon_rpm_repository: http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-3.noarch.rpm

# Configuration
marathon_hostname: "{{ inventory_hostname }}"
marathon_port: 8080
marathon_env_java_opts: '-Xmx512m'
marathon_env_vars:
  - "JAVA_OPTS={{ marathon_env_java_opts }}"

zookeeper_hostnames: "{{ groups['master'][0] }}:2181"
mesos_zookeeper_path: "/mesos"
marathon_zookeeper_path: "/marathon"
mesos_zookeeper_masters: "zk://{{ zookeeper_hostnames }}{{ mesos_zookeeper_path }}"
marathon_zookeeper_state: "zk://{{ zookeeper_hostnames }}{{ marathon_zookeeper_path }}"

# SSL
mesos_ssl_enabled: false
mesos_ssl_support_downgrade: false

# optional
artifact_store: ""
checkpoint: "true"
marathon_mesos_role: ""

marathon_additional_configs: []
#    For example:
#    - name: task_lost_expunge_interval
#      value: 900000
